name: Java CI

on: 
  push:
  pull_request:
    types: [labeled, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package assembly:single
      - uses: actions/upload-artifact@v3
        with:
          name: fat-jar
          path: target/temp-logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'bug') || contains(github.event.head_commit.message, '#deploy') 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world PR!
